baseURL = "https://minducky.github.io/myblog/"
languageCode = "ko-kr"
title = "민덕기록"
enableRobotsTXT = true

[params]
  description = "본인을 기록하기 위해 만든 블로그입니다"
  author = "minducky"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "monokai"
  lineNos = false
